### ISSUE TITLE
diseño de modelo de datos de giros

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/giros_crud#2]
se requiere realizar el modelo de datos para el sistema de giros, para el cual ya se habia realizado un previo [analisis](https://github.com/udistrital/financiera_documentacion/issues/184)

alli ya hay un modelo con vertabelo asi que pedirle a la desarrolladora @Miranda13 que le de acceso para que pueda entrar y editar el modelo

**Comment by NRDaza** [comment]
Se realiza la propuesta del modelo de datos con base a la información y mockups de giros.

![giros_proveedores-2021-02-19_14-31 (1)](https://user-images.githubusercontent.com/34488581/108552677-a22b5180-72bf-11eb-8fc2-b2b2231ca8b9.png)

Las notas narajan corresponde a referencias a otras api como la api_parámetros para las tablas paramétricas o las ordenes de pago que se encuentras en el sistema centras de cuentas.

esta pendiente la socialización del modelo de datos.
(Link Vertabelo)
https://my.vertabelo.com/doc/WUsKmvDcT3iVIHov3gldBxyuUw17P6ZI

**Comment by ManuelMurillo** [comment]
#3 aqui se describe los ajustes realizados en el modelo
