### ISSUE TITLE
socializar modelo de datos de giros

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/giros_crud#3]

**Comment by NRDaza** [comment]
El día 26de febrero del 2021 se realizó la Reunión de socialización del modelo de datos  la cual fue grabada y estuvo presentes @NRDaza @mcrubianot  @fnrojash  @danzola

Enlace [Reunion](https://drive.google.com/file/d/1rzDN882dLnSRutC8zUrMHLT0AplinL-y/view?usp=sharing)

en esta Reunión se socializó el siguiente modelo
![giros_proveedores-2021-02-26_14-47](https://user-images.githubusercontent.com/34488581/109351534-6e17d980-7847-11eb-895a-a8f8755baf98.png)

Al finalizar la Reunión quedaron lo siguientes puntos pendientes:

- [ ]  Eliminar campos sumas debito y crédito de la tabla de contabilización
- [ ]  Para la tabla formas de pago hacer referencia al api_parametros

Por parte de los lineamientos de base de datos el modelo fue aprobado. Falta la verificación de @corio27

**Comment by NRDaza** [comment]
Modelo de datos con los cambios realizados:

![giros_proveedores-2021-02-26_15-35](https://user-images.githubusercontent.com/34488581/109352116-555bf380-7848-11eb-8683-8f2d05e11575.png)
